#!/bin/bash

if [ "$#" = "0"  ]; then
	echo Usage: $0 path-to-image
	exit 1
fi

FILE=$1
shift

exec qemu-system-x86_64 -machine accel=kvm -device edu -device edu -k en-us -smp 4 -m 2000 -hda $FILE -usb -net user,hostfwd=tcp::2222-:22 -net nic,model=e1000 -serial pty -soundhw pcspk "$@"
